---
title: "In-class Exercise 5"
author: "Sindy"
date-modified: "last-modified"
execute:
  echo: true
  eval: true
  warning: false
  freeze: true
---

## Getting started

### Installing and Loading R packages

```{r}
pacman::p_load(tidyverse, readxl, SmartEDA, easystats, gtsummary, ggstatsplot)
```

```{r}
car_resale <- read_xls("./data/ToyotaCorolla.xls", "data")
```

### Data summary

```{r}
summary(car_resale)
```
Or with glimpse:

```{r}
glimpse(car_resale)
```


### List records
```{r}
list(car_resale)
```



## Data overview

Type has 2 arguments:
- Type = 1
- Type = 2...

```{r}
summary1 <- car_resale %>%
  ExpData(type=1)

summary1  # can be further customised (a table/df object)
```
```{r}
summary2 <- car_resale %>%
  ExpData(type=2)

summary2  # can be further customised (a table/df object)
```

```{r}
cols <- c("Mfg_Month", "HP_Bin", "CC_bin", "Doors", "Gears",
           "Cylinders", "Fuel_Type", "Color",
           "Met_Color", "Automatic", "Mfr_Guarantee", "BOVAG_Guarantee",
           "ABS", "Airbag_1", "Airbag_2", 
           "Airco", "Automatic_airco", "Boardcomputer", "CD_Player",
           "Central_Lock", "Powered_Windows", "Power_Steering","Radio",
           "Mistlamps", "Sport_Model", "Backseat_Divider", "Metallic_Rim",
           "Radio_cassette", "Tow_Bar")


car_resale <- read_xls("./data/ToyotaCorolla.xls", "data") %>%
  mutate(Id = as.character(Id)) %>%
  mutate_each_(funs(factor(.)),cols)
```
```{r}
summary(car_resale)
```


```{r}
car_resale %>%
  ExpNumViz(target=NULL,
            nlim=10,
            Page=c(2,2))
```

```{r}
car_resale %>%
  ExpNumViz(target="Price",
            nlim=10,
            Page=c(2,2))
```

Bar plots for all categorial variables
```{r}
#| fig-width: 12
#| fig-height: 10
car_resale %>%
  ExpCatViz(target=NULL,
            col="sky blue",
            clim=10,
            margin=2,
            Page=c(4,4),
            sample=16)
```

```{r}
model <- lm(Price ~ Age_08_04 + Mfg_Year + KM + Weight + Guarantee_Period, data=car_resale)

model
```

```{r}
check_collinearity(model)
```

```{r}
check_c <- check_collinearity(model)
plot(check_c)
```

```{r}
# take out manufacturing year because of collinearlity 
model1 <- lm(Price ~ Age_08_04 + KM + Weight + Guarantee_Period, data=car_resale)
check_normality(model1)
```

```{r}
check_heteroscedasticity(model1)
```

```{r}
#| fig-width: 12
#| fig-height: 8
check_model(model1)
```



2 ways:
1. correlation matrix
2. vif

gtsummary
```{r}
summary(model1)
```


```{r}
tbl_regression(model1, 
               intercept = TRUE)
```

Basic Regression Table
```{r}
tbl_regression(model1, 
               intercept = TRUE) %>%
  add_glance_source_note(
    # "\U03C3" to extract the sigma value
    label = list(sigma ~ "\U03C3"),  # can ignore if you do not want the sigma
    include = c(r.squared, adj.r.squared,
                AIC, statistic,
                p.value, sigma)
  )
```
# Section 2

```{r}
p_model1 <- parameters(model1)

p_model1
```

```{r}
plot(parameters(model1))
```
shows you which one has more uncertrainity or less uncertainity

```{r}
ggcoefstats(model1,
            output="plot")
```






